export const questions = [
  {
    id: 1,
    image: '/images/nps/slide-1.webp',
    question: 'How likely are<br>you to recommend<br>Laundry Sauce to<br>a friend?',
    type: 'scale',
    min: 0,
    max: 10,
    minLabel: 'Not Likely',
    maxLabel: 'Extremely Likely',
  },
  {
    id: 2,
    image: '/images/nps/slide-2.webp',
    question: 'Awesome!',
    subtitle: 'What do you love most about Laundry Sauce?',
    description: "We'd love to know what stood out or made your experience great.",
    type: 'text',
    placeholder: 'Tell us what you love...',
    showIf: { field: 'nps_score', op: 'between', min: 9, max: 10 },
  },
  {
    id: 3,
    image: '/images/nps/slide-2.webp',
    question: 'What would make you more likely to recommend us?',
    description: 'Your input helps us take the next step from "good" to "amazing."',
    type: 'text',
    placeholder: 'Tell us what would help...',
    showIf: { field: 'nps_score', op: 'between', min: 7, max: 8 },
  },
  {
    id: 4,
    image: '/images/nps/slide-2.webp',
    question: 'Oh no! \u{1F614}',
    subtitle: 'How could we make things better?',
    description: 'We really want to understand what went wrong so that we can improve.',
    type: 'text',
    placeholder: 'Tell us how we can improve...',
    showIf: { field: 'nps_score', op: 'between', min: 0, max: 6 },
  },
  {
    id: 5,
    image: '/images/nps/slide-3.webp',
    type: 'thankyou',
    heading: 'Thank you for<br>your feedback!',
    body: 'Want to discover your new favorite scent?',
    linkText: 'Scent Quiz',
    linkUrl: 'https://laundrysauce.com',
  },
]
